### ISSUE TITLE
include .js and .jsx files in tsLoader.test

### ISSUE THREAD

**Issue by micimize** [SZzzzz/react-scripts-ts-antd#3]
[tsLoader.test](https://github.com/SZzzzz/react-scripts-ts-antd/blob/master/config/loaders.js#L54) only matches typescript files, but I think it would be best to match on `/\.(tsx?|jsx?)$/` in case `compilerOptions.allowJs` is set to `true` in the `tsconfig.json`.

**Comment by SZzzzz** [comment]
You are right. I will add `babel-loader` in next version. Thanks for your advice.
