### ISSUE TITLE
Incorrect types

### ISSUE THREAD

**Issue by zachdixon** [SZzzzz/react-scripts-ts-antd#4]
I've been trying to get an app working with create-react-app, react-app-rewired, typescript, and antd, but was running into some compiling issues with incorrect types.

I found this package and started a new project with it and getting the same errors:
```
(28,81): Type '{ className: string; style: { transition: string | boolean; msTransform: string; WebkitTransform:...' does not satisfy the constraint 'HTMLAttributes<HTMLElement>'.
  Types of property 'style' are incompatible.
    Type '{ transition: string | boolean; msTransform: string; WebkitTransform: string; transform: string; }' is not assignable to type 'CSSProperties | undefined'.
      Type '{ transition: string | boolean; msTransform: string; WebkitTransform: string; transform: string; }' is not assignable to type 'CSSProperties'.
        Types of property 'transition' are incompatible.
          Type 'string | boolean' is not assignable to type 'string | undefined'.
            Type 'true' is not assignable to type 'string | undefined'.
```

**Comment by p0rsche** [comment]
Have a look at https://github.com/SZzzzz/react-scripts-ts-antd/issues/4 discussion.
Temporary solution might be to have "skipLibCheck": true in tsconfig.json until they will patch ScrollNumber.d.ts

**Comment by SZzzzz** [comment]
Just like @p0rsche said. You have to set `skipLibCheck` option.
